name: run-tests

# Only run this when the branch changes
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'hooks/**'
      - 'README.md'

# This job installs dependencies, builds the code and runs the hand rolled Python test framework
jobs:
  run-tests:
    # Please don't run on MacOS runners, they are not generally worth the cost
    # If you believe you need MacOS runners, please contact the course staff first
    # It's okay to run on Windows runners, but they are often slower than Linux runners
    # to get results.

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install build dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev build-essential cmake ninja-build
          # libcunit1-dev is likely no longer needed if all tests move to GTest
          # sudo apt-get install -y libcunit1-dev 

    - name: Configure CMake
      run: |
          # Using Ninja for potentially faster builds
          cmake -B build -S . -G Ninja
      
    - name: Build all targets (including tests)
      run: |
          cmake --build build --parallel

    # - name: Build the GA library (Handled by 'Build all targets')
    #   run: |
    #       make geneticAlgorithm

    # - name: Build the circuit optimizer (Handled by 'Build all targets')
    #   run: |
    #       make Circuit_Optimizer

    - name: Run tests with CTest
      working-directory: build # CTest should usually be run from the build directory
      run: |
          ctest -VV --output-on-failure